card/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.cardDetail, name="card-detail"),
    path("add/<int:product_id>", views.addCard, name="add-card"),
    path("remove/<int:product_id>", views.removeCard, name="remove-card"),
]

order/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("create/", views.order_create, name="order-create"),
]

suqakosti/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("product.urls")),
    path("card/", include("card.urls")),
    path("orders/", include("order.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/models.py
from django.db import models
from product.models import Product
from django.forms import ModelForm

from phonenumber_field.modelfields import PhoneNumberField

ADDRESSES = (
    ("", "إختار الحي"),
    ("abushrif", "ابو شريف م3"),
    ("square 31", "مربع 31"),
    ("square 32", "مربع 32"),
    ("square 29", "مربع 29"),
    ("square 27", "مربع 27"),
    ("square 26", "مربع 26"),
    ("square 28", "مربع 28"),
    ("square 34", "مربع 34"),
    ("square 42", "مربع 42"),
    ("square 43", "مربع 42"),
    ("alandlos", "الاندلس"),
    ("alnsry", "النصري"),
    ("square 44", "مربع 44"),
    ("square 39", "مربع 39"),
    ("square 46", "مربع 46"),
    ("square 47", "مربع 47"),
    ("alhala ", "الحلة الجديدة"),
    ("alshati", "الشاطئ"),
)


# Create your models here.
class Order(models.Model):
    FullName = models.CharField(max_length=200, verbose_name=("الاسم بالكامل "),)

    PhoneNumber1 = models.CharField(max_length=10, verbose_name=("رقام الهاتف"))
    PhoneNumber2 = models.CharField(
        max_length=10, verbose_name=("رقام هاتف اختياري"), blank=True
    )
    # phoneNumber1 = PhoneNumberField(max_length=10, verbose_name=("رقم الهاتف"))
    # PhoneNumber2 = PhoneNumberField(
    #   max_length=10, blank=True, verbose_name=("رقم هاتف اخر ")
    # )
    ORDAddressEra = models.CharField(
        max_length=200, choices=ADDRESSES, verbose_name=(" المنطقة"),
    )
    ORDAddress = models.TextField(verbose_name=(" العنوان بالتفصيل"),)
    ORDACreated = models.DateTimeField(auto_now_add=True, verbose_name=("تاريخ الطلب"),)
    ORDAUpdate = models.DateTimeField(auto_now=True, verbose_name=("تاريخ تعديل الطلب"))
    ORDPaid = models.BooleanField(default=False)

    class Meta:
        ordering = ("-ORDACreated",)
        verbose_name = "طلب المنتج"
        verbose_name_plural = "طلبات المنتجات"

    def __str__(self):
        return f" Order {self.id}"

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, verbose_name="items", on_delete=models.CASCADE)
    ORDIProduct = models.ForeignKey(
        Product, verbose_name="order_items", on_delete=models.CASCADE
    )

    ORDIPrice = models.DecimalField(max_digits=10, decimal_places=2)
    ORDIQuantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return str(self.id)

    def get_cost(self):
        return self.ORDIPrice * self.ORDIQuantity

order/forms.py
from django import forms
from .models import Order

# from phonenumber_field.modelfields import PhoneNumberField


class OrderCreateForm(forms.ModelForm):
    # PhoneNumber1 = forms.CharFaild()
    # PhoneNumber2 = PhoneNumberField()

    class Meta:
        model = Order
        fields = [
            "FullName",
            "PhoneNumber1",
            "PhoneNumber2",
            "ORDAddressEra",
            "ORDAddress",
        ]

order/views.py
from django.shortcuts import render
from card.card import Card
from .forms import OrderCreateForm
from .models import OrderItem

# Create your views here.
def order_create(request):
    card = Card(request)
    if request.method == "POST":
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in card:
                OrderItem.objects.create(
                    order=order,
                    ORDIProduct=item["product"],
                    ORDIPrice=item["price"],
                    ORDIQuantity=item["quantity"],
                )
            card.clear()
            return render(request, "order/created_order.html", {"order": order},)
    else:
        form = OrderCreateForm()
    return render(request, "order/create_order.html", {"card": card, "form": form})

order/templates/order/create_order.html
{% extends 'base.html' %}
{% block title %}إرسال الطلب{% endblock %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}

<form method="POST">
    <fieldset class="form-group">
        <legend>ادخل البيانات</legend>
        {% csrf_token %}
        {{form | crispy}}
    </fieldset
    <div class="form-group">
        <button class="btn btn-outline-info" type="submit">إرسال الطلب</button>
    </div>
</form>


{% comment %} <div class="row">
    <div class="col-4">
    <div class="text-center">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom ">Checkout</legend>

                <div id="div_id_FirstName" class="form-group">
                    <label for="id_FirstName" class="requiredField">الاسم الأول </label>
                    <input type="text" name="FirstName" maxlength=200 class="textinput textInput form-control" required id="FirstName">
                </div>

                <div id="div_id_LastName" class="form-group">
                    <label for="id_LastName" class="requiredField">الاسم الأول </label>
                    <input type="text" name="LasttName" maxlength=200 class="textinput textInput form-control" required id="LasttName">
                </div>

                <div id="div_id_PhoneNumber1" class="form-group">
                    <label for="id_PhoneNumber1" class="requiredField">الاسم الأول </label>
                    <input type="text" name="PhoneNumber1" maxlength=200 class="textinput textInput form-control" required id="PhoneNumber1">
                </div>

                <div id="div_id_PhoneNumber2" class="form-group">
                    <label for="id_PhoneNumber2" class="requiredField">الاسم الأول </label>
                    <input type="text" name="PhoneNumber2" maxlength=200 class="textinput textInput form-control" required id="PhoneNumber2">
                </div>

                <div id="div_id_ORDAddressEra" class="form-group">
                    <label for="id_ORDAddressEra" class="requiredField">الاسم الأول </label>
                    <select name="ORDAddressEra" maxlength=200 class="textinput textInput form-control" required id="ORDAddressEra">

                    </select>
                </div>

                <div id="div_id_FirstName" class="form-group">
                    <label for="id_FirstName" class="requiredField">الاسم الأول </label>
                    <input type="text" name="FirstName" maxlength=200 class="textinput textInput form-control" required id="FirstName">
                </div>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">إتمام الطلب</button>
            </div>
        </form>
    </div>
    </div>
</div> {% endcomment %}

{% endblock content %}

order/templates/order/created_order.html
{% extends 'base.html' %}
{% block title %}لقد تم إستلام طلبك {% endblock %}
{% block content %}

<h1>شكرا لشراءك من سوق كوستي الإلكتروني </h1>

<p> سوف يصلك الطلب خلال ساعة او اثنين</p>

{% endblock content %}